@startuml class_diagram

' Setting ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

' Components '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


package "PyPI Libraries" {
    class bmw-lobster {

    }

    class doxmlparser {

    }

    class rich {
      
    }
}

package lobster_doxygen {
    class main {

    } 

    note top of main
        Entry point and
        argument handling.
    end note

    class "doxygen_to_lobster_converter" as converter {
    }

    note top of converter
        Conversion processor
    end note

    class "write_lobster_common_interchange_format_file" as writer {

    }

    note top of writer
        Lobster interchange
        format output
        file writer.
    end note

    class "get_lobster_items_from_doxygen_xml_folder" as reader {
    }


    note left of reader
        Doxygen XML 
        input reader.
    end note
    class "rule_check" as checker{

    }

    note top of checker
        Rule based checks for
        LobsterItems.
    end note

    class LobsterItem {

    }

        note top of LobsterItem
        Lobster item
        representation.
    end note

}

package Utilities {
        class Printer {
        }

        class Version {
        }

        class utils 

        utils .d[hidden].> Version
        Version .d[hidden].> Printer
    }
' Flows ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


main .d.> converter
converter .d.> reader
converter .d.> writer
converter .r.> checker
converter "*" o.l.> LobsterItem 

reader .d.> doxmlparser
writer .d.> "bmw-lobster"

Printer .d.> rich
@enduml