@startuml context_diagram

' Setting ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

skinparam linetype ortho
<style>
component {
    BackgroundColor #lightgreen
}
.config {
    BackgroundColor #orange
}

.cuif {
    BackgroundColor #LightBlue
}
</style>

' Components '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package "Input" {
    file "Source file(s) supported by Doxygen\n(e.g. *cpp, *c, *.java), with Doxygen comments" as source_code <<files>>
    note left of source_code
        With implements and justification
        links to TRLC requirements 
    end note
}

package "Doxygen Toolchain" {
    component "doxygen" as doxygen <<tool>>
    file "Doxyfile" as doxygen_configuration <<config>>

    note left of doxygen_configuration
        With
        - Aliases for 
         * implements
         * justification
        - Extract all
        - XML output enabled. 
    end note

    file "XML output" as xml_output <<files>>
}

package LOBSTER {
    package "System" {
        component "lobster-doxygen" as lobster_doxygen <<tool>> 
    }
    file "LOBSTER common interchange\nformat file (*.json)" as lobster_configuration_file 
}

' Flows ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

source_code .down.> doxygen :  <<flow>>
doxygen ..left..> doxygen_configuration : <<use>>
doxygen .down.> xml_output : <<generates>>
xml_output .down.> lobster_doxygen : <<input>>
lobster_doxygen .down.> lobster_configuration_file : <<generates>>

@enduml