@startuml use_cases

' Setting ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

left to right direction
skinparam linetype ortho

<style>
actor {
  BackgroundColor #E3F2FD
  LineColor #1E88E5
  FontColor #0D47A1
  FontWeight bold
}

usecase {
  BackgroundColor #E8F5E9
  BorderColor #388E3C
  FontColor #1B5E20
  RoundCorner 20
  FontSize 12
  FontStyle bold
}
</style>

' Components '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

actor "User" as user
file "Doxygen XML files (*.xml)" as doxygen_xml <<files>>

rectangle "System" {
    usecase "Show tool version" as uc_version
    usecase "Print command overview to console" as uc_help
    usecase "Transform XML to LOBSTER common interchange file" as uc_transform
    usecase "Phrase Doxygen XML" as uc_parse_xml
    usecase "Generate LOBSTER common interchange file" as uc_output
}

file "LOBSTER common interchange format file" as lobster_file <<file>>

' Flows ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

user --> uc_help : request help 
user --> uc_version : request version 
user --> uc_transform : request conversion
doxygen_xml --> uc_transform
uc_transform ..> uc_output : <<includes>>
uc_transform ..> uc_parse_xml : <<includes>>
uc_output --> lobster_file 

@enduml